dist: trusty
language: generic
services:
    - docker

before_install:
    - docker pull barnybug/elasticsearch
    - docker run -d -p 9200:9200 -p 9300:9300 barnybug/elasticsearch:latest

install: true

script: 
    - docker ps -a
    - echo "re-test"
